### PR TITLE
Add Russian localization

### PR DESCRIPTION
**Pull request by talentlessguy**
this PR adds Russian translations for gotop UI.

### CODE REVIEW

**Comment by xxxserxxx** [comment]
Hi @talentlessguy @kitt3911 -- you both submitted Russian translations within a day of each other!  Would you mind discussing your patches and either merge them into one, or suggest which I should merge?  I'm (unfortunately) not qualified to review Russian!

@kitt3911's PR is https://github.com/xxxserxxx/gotop/pull/172

Thank you both.

**Comment by kitt3911** [comment]
Hi @xxxserxxx, I'm sure @talentlessguy's translation is more accurate.

**Comment by talentlessguy** [comment]
@kitt3911 yey thx :D

to add, I have translated more parts so prob my PR is in favor haha

**Comment by kitt3911** [comment]
@talentlessguy , one day we will definitely compete again ahah 😉😉😉

**Comment by xxxserxxx** [comment]
@kitt3911 , @talentlessguy -- thanks, both of you!

**Pull request merged**
